spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update  # or your preferred value
  tasks:
    scheduled:
      enabled: true
      cron: "0 * * * * *"
  upload:
    dir: "src/main/resources/files-to-import"
  batch:
    size: 100
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
server:
  port: 8080
aws:
  serviceEndpoint: http://localhost:4566
  signingRegion: eu-north-1