spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # or your preferred value
    open-in-view: false
  h2:
    console:
      enabled: true  # This line enables the H2 console for development
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
  upload:
    dir: "src/main/resources/files-to-import"
  integration:
    jdbc:
      initialize-schema: always
server:
  port: 8080
file-storage:
  solution: local

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
