# Log SQL statements to SLF4J Logger
module.log=com.p6spy.engine.spy.appender.Slf4JLogger

# Format of the log message
p6spy.config.logMessageFormat=full

# Log level for SQL statements
p6spy.config.logLevel=DEBUG
